// AUTO GENERATED FILE, DO NOT EDIT!
// This file has been generated by nt-status-gen from https://github.com/Janrupf/nt-status-gen
//
// Used compiler: MSVC version 19.28.29337.0
// Targeted OS: Windows version 10.0.19044

#pragma once

#include <cstdint>
#include <string>

namespace NtStatus {
   bool lookupNtStatusCodeName(uint64_t code, std::string &nameOut);
}
