add_executable(GrabJRE GrabJRE.cpp)
target_link_libraries(GrabJRE Launcher_logic Qt5::Core)

if(DEFINED Launcher_BINARY_RPATH)
    SET_TARGET_PROPERTIES(GrabJRE PROPERTIES INSTALL_RPATH "${Launcher_BINARY_RPATH}")
endif()

install(TARGETS GrabJRE
    BUNDLE DESTINATION ${BUNDLE_DEST_DIR} COMPONENT Runtime
    LIBRARY DESTINATION ${LIBRARY_DEST_DIR} COMPONENT Runtime
    RUNTIME DESTINATION ${BINARY_DEST_DIR} COMPONENT Runtime
)
